/* Modelagem Básica */

CLIENTE

NOME - CARACTER(30)
CPF - NUMERICO(11)
EMAIL - CARACTER(30)
ENDERECO - CARACTER(100)
SEXO - CARACTER(1)


/* Processos de modelagem */

/* FASE 01 3 FASE 02 - AD ADM DE DADOS */
MODELAGEM CONCEITUAL - RASCUNHO
MODELAGEM LOGICA - QUALQUER PROGRAMA DE MODELAGEM

/* FASE 03 - DBA / AD */
MODELAGEM FISICA - SCRIPTS


ENTIDADE = TABELA 

